version: '3.4'

services:
  mysql-transaction:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password

  banking.operation.transaction.api:
    image: ${DOCKER_REGISTRY-}bankingoperationtransactionapi
    build:
      context: .
      dockerfile: Banking.Operation.Transaction.Api/Dockerfile
      
networks:
  default:
    external: true
    name: bankingoperation-client-api_backend